### PR TITLE
Testing HDF5 output/pytables.

### PR DESCRIPTION
**Pull request by astronomerritt**
I have added pytables to setup.cfg to enable HDF5 output. I expect this will cause github's automated tests to fail due to #353. Currently, all tests run successfully on my machine using Python 3.11.

## Review Checklist for Source Code Changes

- [x] Does pip install still work?
- [x] Have you written a unit test for any new functions?
- [x] Do all the units tests run successfully?
- [x] Does SurveySimPP run successfully on a test set of input files/databases?
- [x] Have you used flake8 on the files you have updated to confirm python programming style guide enforcement? (You can ignore line length warnings: flake8 --ignore=E501,E126,E228,E228,E133,W503)

### CODE REVIEW

**Comment by mschwamb** [comment]
@astronomerritt all the tests passed

**Comment by astronomerritt** [comment]
Yep, because the test environments pip install everything - they were failing before because I had the wrong name for pytables in the setup.cfg file. (It's pytables on conda, tables on pip. I hate it when that happens.) Sorry, totally forgot to mention that part in the chaos of trying to fix it.

You can merge this pull request - HDF5 output is working now, and it's being unit tested.

**Comment by mschwamb** [comment]
Is it possible to make these separate pull requests for then other additions?. Because if pytables issue is not resolved in conda then this shouldn't be merged until we know it's not causing issues with install

**Comment by astronomerritt** [comment]
This pull request does not change the installation in any significant way apart from adding pytables to the requirements in setup.cfg, which is needed to make HDF5 output work.

The issue we're having in #353 is with conda installing sbpy, which isn't related to what's included in the repo at all. I've updated the title to reflect that.

(Pytables was relevant at first because adding pytables to my environment is what brought this issue to my attention. However, _pytables isn't the problem_.)

A fresh install works fine on my machine, anyway.

If you still want it separated, close the request and I'll revert on my end - this will however mean that HDF5 output won't work.

**Comment by mschwamb** [comment]
Can a clean install be done with conda and pip installing the package in this pull request (no special pip install of sbpy)? If that is not the case these need to be split.

**Comment by astronomerritt** [comment]
Yes, by following the current instructions in the docs - creating the conda environment, then using pip install -e . to install the SSPP requirements. No special instructions needed.

However, even if I revert this pull request, we will still have the same problem with sbpy. It will always need to be pip installed until we've worked out what's causing the conda installation to generate warnings during tests. This pull request doesn't do anything to alter the problem. It just adds pytables to setup.cfg.

**Pull request merged**
